FileVersion = 1

[Project]
Name = "Willow"
StartupObject = "BindingGeneratorHpp.Program"
DefaultNamespace = "BindingGeneratorHpp"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/libclang.dll"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/libclang.dll"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)/libclang.dll"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)/libclang.dll"]
